hyperparameters:
  epochs: 40
  batch_size: 64

  lr: 0.001
  momentum: 0.9 

  num_workers: 4

paths:
  train_dir: 'data/cifar10/train'
  test_dir: 'data/cifar10/test'
  model_path: 'weights/checkpoint.pth'