hyperparameters:
  epochs: 60
  batch_size: 512
  lr: 0.008
  weight_decay: 0.0001
  num_workers: 2

paths:
  train_dir: 'data/cifar10/train'
  test_dir: 'data/cifar10/test'
  model_path: 'weights/checkpoint.pth'