hyperparameters:
  epochs: 50
  batch_size: 64

  lr: 0.0003
  #momentum: 0.9
  weight_decay: 0.0005
  betas: [0.9,0.995]

  num_workers: 8

paths:
  train_dir: 'data/cifar10/train'
  test_dir: 'data/cifar10/test'
  model_path: 'weights/checkpoint.pth'