hyperparameters:
  epochs: 100
  batch_size: 128
  early_stopping_patience: 10
  delta: 0.005
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.00001
  num_workers: 8

paths:
  train_dir: "data/cifar10/train"
  test_dir: "data/cifar10/test"
  model_path: "weights/checkpoint.pth"
