hyperparameters:
  epochs: 50
  batch_size: 16

  lr: 0.001
  #momentum: 0.9 
  weight_decay: 0.01
  num_workers: 8

paths:
  train_dir: 'data/cifar10/train'
  test_dir: 'data/cifar10/test'
  model_path: 'weights/checkpoint.pth'