hyperparameters:
  epochs: 30
  batch_size: 16

  lr: 0.001
  momentum: 0.9 

  num_workers: 4

  val_split: 0.1   # <-- add this line
   
paths:
  train_dir: 'data/cifar10/train'
  test_dir: 'data/cifar10/test'
  model_path: 'weights/checkpoint.pth'