[project]
name = "inmindcnn"
version = "0.1.0"
requires-python = ">=3.11,<3.12"

dependencies = [
    "einops>=0.8.1",
    "pyyaml>=6.0.2",
    "torch>=2.2.0",  # stable GPU version for cu118
    "torchvision>=0.17.0",
    "torchaudio>=2.2.0",
    "tqdm>=4.67.1",
]
